name: 'ReleaseSystemSnap'
description: 'Release a system snap to the beta channel'
author: 'Alfonso Sanchez-Beato'

inputs:
  architectures:
    description: Comma separated list of architectures to override the default
    required: false
    type: string
    default: ""
  snapcraft_channel:
    description: Snapcraft snap installation channel
    required: false
    type: string
    default: ""

runs:
  using: "composite"
  steps:
    - name: Cleanup job workspace
      shell: bash
      run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
    - name: Checking out
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
        # We need the full history to create the changelog
        fetch-depth: 0
    - name: Checking out CICD scripts
      uses: actions/checkout@v3
      with:
        repository: snapcore/system-snaps-cicd-tools
        ref: main
        path: cicd
    - name: Release
      shell: bash
      env:
        BUILD_ARCHITECTURES: ${{ inputs.architectures }}
        SNAPCRAFT_CHANNEL: ${{ inputs.snapcraft_channel }}
      run: |
        printf "Releasing from %s\n" "${{ github.ref_name }}"
        # TODO better probably to have a local install
        mkdir -p ~/bin
        wget -q https://github.com/mikefarah/yq/releases/download/v4.30.8/yq_linux_amd64.tar.gz \
            -O - | tar xz
        mv yq_linux_amd64 ~/bin/yq
        wget -q https://storage.googleapis.com/snapd-spread-tests/spread/spread-plus-amd64.tar.gz \
            -O - | tar xz
        mv spread ~/bin/spread
        export PATH=$PATH:~/bin/
        ./cicd/workflows/snap-release.sh "${{ github.ref_name }}" "${{ runner.temp }}"
        for s in "${{ runner.temp }}"/*_*.snap; do
            s=${s##*/}
            SNAP_NAME=${s%%_*}
            break
        done
        echo "SNAP_NAME=$SNAP_NAME" >> $GITHUB_ENV
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.SNAP_NAME }}-snaps
        path: ${{ runner.temp }}/${{ env.SNAP_NAME }}_*.snap
    - name: Publish the snaps to beta channel
      shell: bash
      run: |
        ref=${{ github.ref_name }}
        track=${ref##*-}
        if [ -z "$track" ]; then
            printf "ERROR: no track has been specified\n"
            exit 1
        fi
        ./cicd/workflows/snap-publish.sh "${{ runner.temp }}" \
            ${{ env.SNAP_NAME }} "$track"/beta
