name: 'RebuildBase'
description: 'Rebuild a base snap and publish to the edge channel on changes'
author: 'Alfonso Sanchez-Beato'

inputs:
  architectures:
    description: Comma separated list of architectures to override the default
    required: false
    type: string
    default: ""
  snapcraft_channel:
    description: Snapcraft snap installation channel
    required: false
    type: string
    default: ""
  branch:
    description: Branch to release from
    required: false
    type: string
    default: "${{ github.ref_name }}"
  publish:
    description: Whether to publish built snaps to the store
    required: false
    type: boolean
    default: true
  build-variant:
    description: Variant to build, can be "regular", "fips" or "cloud-init"
    required: false
    type: string
    default: regular

outputs:
  snap_name:
    description: Name of the built snap (empty when no build was triggered)
    value: ${{ steps.release.outputs.snap_name }}
  snap_artifact:
    description: Artifact basename used for uploaded snaps
    value: ${{ steps.release.outputs.snap_artifact }}

runs:
  using: "composite"
  steps:
    - name: Cleanup job workspace
      shell: bash
      run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
    - name: Checking out
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
        # We need the full history and tags to create the changelog
        fetch-depth: 0
    - name: Checking out CICD scripts
      uses: actions/checkout@v4
      with:
        repository: snapcore/system-snaps-cicd-tools
        ref: main
        path: cicd
    - name: Release
      id: release
      shell: bash
      env:
        BUILD_ARCHITECTURES: ${{ inputs.architectures }}
        SNAPCRAFT_CHANNEL: ${{ inputs.snapcraft_channel }}
      run: |
        set -x
        printf "Releasing from %s\n" branch "${{ inputs.branch }}"
        BUILD_VARIANT=${{ inputs.build-variant }}
        sudo DEBIAN_FRONTEND=noninteractive apt-get install yq -yqq
        snap_name=$(yq -r .name snapcraft.yaml)
        if [ "$snap_name" = core ]; then
            series=''
        else
            series=${snap_name#core}
        fi

        ARTIFACT_SUFFIX=""
        if [ "$BUILD_VARIANT" != regular ]; then
            ARTIFACT_SUFFIX=-"$BUILD_VARIANT"
        fi

        ./cicd/workflows/build-base-on-changes.py --output-dir="${{ runner.temp }}" --build-variant="$BUILD_VARIANT" --debug "$series"

        # TODO run spread tests on built snaps before publishing

        shopt -s nullglob
        SNAP_NAME=
        for s in "${{ runner.temp }}"/*_*.snap; do
            s=${s##*/}
            SNAP_NAME=${s%%_*}
            break
        done
        shopt -u nullglob
        if [ -z "$SNAP_NAME" ]; then
            printf "No build has been triggered\n"
        fi
        SNAP_ARTIFACT="$SNAP_NAME""$ARTIFACT_SUFFIX"

        echo "snap_name=$SNAP_NAME" >> "$GITHUB_OUTPUT"
        echo "snap_artifact=$SNAP_ARTIFACT" >> "$GITHUB_OUTPUT"
    - name: Upload artifacts
      if: ${{ steps.release.outputs.snap_name != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.release.outputs.snap_artifact }}-snaps
        path: ${{ runner.temp }}/${{ steps.release.outputs.snap_name }}_*.snap
    - name: Publish the snaps to edge channel
      if: ${{ steps.release.outputs.snap_name != '' && inputs.publish }}
      shell: bash
      run: |
        CHANNEL="latest/edge"
        BUILD_VARIANT=${{ inputs.build-variant }}
        if [ "$BUILD_VARIANT" = fips ]; then
          CHANNEL="fips-updates/edge"
        elif [ "$BUILD_VARIANT" = cloud-init ]; then
          CHANNEL="cloud-init/edge"
        fi

        ./cicd/workflows/snap-publish.sh "${{ runner.temp }}" \
            ${{ steps.release.outputs.snap_name }} $CHANNEL
