name: 'RebuildBase'
description: 'Rebuild a base snap and publish to the edge channel on changes'
author: 'Alfonso Sanchez-Beato'

inputs:
  architectures:
    description: Comma separated list of architectures to override the default
    required: false
    type: string
    default: ""
  snapcraft_channel:
    description: Snapcraft snap installation channel
    required: false
    type: string
    default: ""

runs:
  using: "composite"
  steps:
    - name: Cleanup job workspace
      shell: bash
      run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
    - name: Checking out
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
        # We need the full history and tags to create the changelog
        fetch-depth: 0
    - name: Checking out CICD scripts
      uses: actions/checkout@v3
      with:
        repository: snapcore/system-snaps-cicd-tools
        ref: main
        path: cicd
    - name: Release
      shell: bash
      env:
        BUILD_ARCHITECTURES: ${{ inputs.architectures }}
        SNAPCRAFT_CHANNEL: ${{ inputs.snapcraft_channel }}
      run: |
        set -x
        printf "Releasing from %s\n" "${{ github.ref_name }}"
        sudo DEBIAN_FRONTEND=noninteractive apt-get install yq -yqq
        snap_name=$(yq -r .name snapcraft.yaml)
        if [ "$snap_name" = core ]; then
            series=''
        else
            series=${snap_name##*-}
        fi

        ./cicd/workflows/build-base-on-changes.py --output-dir="${{ runner.temp }}" --debug "$series"

        # TODO run spread tests on built snaps before publishing

        for s in "${{ runner.temp }}"/*_*.snap; do
            s=${s##*/}
            SNAP_NAME=${s%%_*}
            break
        done
        echo "SNAP_NAME=$SNAP_NAME" >> $GITHUB_ENV
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.SNAP_NAME }}-snaps
        path: ${{ runner.temp }}/${{ env.SNAP_NAME }}_*.snap
    - name: Publish the snaps to edge channel
      shell: bash
      run: |
        ref=${{ github.ref_name }}
        ./cicd/workflows/snap-publish.sh "${{ runner.temp }}" \
            ${{ env.SNAP_NAME }} latest/edge
