name: 'PublishToEdgeSystemSnap'
description: 'Publish system snap to edge channel'
author: 'Alfonso Sanchez-Beato'

inputs:
  architectures:
    description: Comma separated list of architectures to override the default
    required: false
    type: string
    default: ""
  run_tests:
    description: Run spread tests
    required: false
    type: boolean
    default: true
  spread_suites:
    description: Spread test suites to run
    required: false
    type: string
    default: ""
  track:
    description: Track to publish to
    required: false
    type: string
    default: ""
  snapcraft_channel:
    description: Snapcraft snap installation channel
    required: false
    type: string
    default: ""
  publish:
    description: Publish the snaps to the edge channel
    required: false
    type: boolean
    # Even though publishing directly from this action does not work, leave
    # this on by default so that other consumers are actually notified that the
    # publishing did not succeed.
    default: true

outputs:
  snap_name:
    description: Name of the built snap
    value: ${{ steps.build.outputs.snap_name }}
  channel:
    description: Store channel the snap is published to
    value: ${{ steps.build.outputs.channel }}
  artifact:
    description: Name of the uploaded artifact containing the snaps
    value: ${{ steps.build.outputs.artifact }}

runs:
  using: "composite"
  steps:
    - name: Cleanup job workspace
      shell: bash
      run: |
        rm -rf "${{ github.workspace }}"
        mkdir "${{ github.workspace }}"
    - name: Checking out
      uses: actions/checkout@v3
    - name: Checking out CICD scripts
      uses: actions/checkout@v3
      with:
        repository: snapcore/system-snaps-cicd-tools
        ref: main
        path: cicd
    - name: Build snap
      id: build
      shell: bash
      env:
        BUILD_ARCHITECTURES: ${{ inputs.architectures }}
        SNAPCRAFT_CHANNEL: ${{ inputs.snapcraft_channel }}
        REF: ${{ github.ref_name }}
        OVERRIDE_TRACK: ${{ inputs.track }}
      run: |
        # Compute channel before building to fail fast
        track=${REF##*-}
        if [ -n "$OVERRIDE_TRACK" ]; then
            echo "Overriding track to $OVERRIDE_TRACK"
            track="$OVERRIDE_TRACK"
        fi
        if [ -z "$track" ]; then
            printf "ERROR: no track has been specified\n"
            exit 1
        fi

        # We are inside of the checked out repo
        ./cicd/workflows/snap-build.sh "$RUNNER_TEMP"
        for s in "${{ runner.temp }}"/*_*.snap; do
            s=${s##*/}
            SNAP_NAME=${s%%_*}
            break
        done
        echo "SNAP_NAME=$SNAP_NAME" >> $GITHUB_ENV
        echo "snap_name=$SNAP_NAME" >> "$GITHUB_OUTPUT"
        echo "channel=$track/edge" >> "$GITHUB_OUTPUT"
        echo "artifact=$SNAP_NAME-snaps" >> "$GITHUB_OUTPUT"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build.outputs.artifact }}
        path: ${{ runner.temp }}/${{ env.SNAP_NAME }}_*.snap
    - name: Run spread tests
      # see https://github.com/actions/runner/issues/1483
      if: ${{ inputs.run_tests == true || inputs.run_tests == 'true' }}
      shell: bash
      run: |
        printf "Running spread tests\n"
        mkdir -p ~/bin
        wget -q https://storage.googleapis.com/snapd-spread-tests/spread/spread-plus-amd64.tar.gz \
            -O - | tar xz
        mv spread ~/bin/spread
        export PATH=$PATH:~/bin/
        # TODO tests for other archs?
        cp "${{ runner.temp }}"/${{ env.SNAP_NAME }}_*_amd64.snap .
        suites="${{ inputs.spread_suites }}"
        if [ -z "$suites" ]; then
            echo "Using default spread suite"
            spread google:
        else
            spread $suites
        fi
    - name: Discard spread workers
      shell: bash
      if: always()
      run: |
        shopt -s nullglob
        for r in .spread-reuse.*.yaml; do
            spread -discard -reuse-pid="$(printf "$r\n" | grep -o -E '[0-9]+')"
        done
    - name: Publish the snaps to edge channel
      if: ${{ inputs.publish == true || inputs.publish == 'true' }}
      shell: bash
      run: |
        echo "Publishing needs extra work: please see https://github.com/canonical/system-snaps-cicd-tools/issues/49"
        exit 1
