name: 'TestSystemSnap'
description: 'Build and test a system snap'
author: 'Alfonso Sanchez-Beato'

inputs:
  architectures:
    description: Comma separated list of architectures to override the default
    required: false
    type: string
    default: ""
  run_tests:
    description: Run spread tests
    required: false
    type: boolean
    default: true
  spread_suites:
    description: Spread test suites to run
    required: false
    type: string
    default: ""
  snapcraft_channel:
    description: Snapcraft snap installation channel
    required: false
    type: string
    default: ""

runs:
  using: "composite"
  steps:
    - name: Cleanup job workspace
      shell: bash
      run: |
        rm -rf "${{ github.workspace }}"
        mkdir "${{ github.workspace }}"
    - name: Checking out
      uses: actions/checkout@v3
    - name: Checking out CICD scripts
      uses: actions/checkout@v3
      with:
        repository: snapcore/system-snaps-cicd-tools
        ref: main
        path: cicd
    - name: Build snap
      shell: bash
      env:
        BUILD_ARCHITECTURES: ${{ inputs.architectures }}
        SNAPCRAFT_CHANNEL: ${{ inputs.snapcraft_channel }}
      run: |
        # We are inside of the checked out repo
        ./cicd/workflows/snap-build.sh "${{ runner.temp }}"
        for s in "${{ runner.temp }}"/*_*.snap; do
            s=${s##*/}
            SNAP_NAME=${s%%_*}
            break
        done
        echo "SNAP_NAME=$SNAP_NAME" >> $GITHUB_ENV
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.SNAP_NAME }}-snaps
        path: ${{ runner.temp }}/${{ env.SNAP_NAME }}_*.snap
    - name: Run spread tests
      # see https://github.com/actions/runner/issues/1483
      if: ${{ inputs.run_tests == true || inputs.run_tests == 'true' }}
      shell: bash
      run: |
        printf "Running spread tests\n"
        # TODO tests for other archs?
        cp "${{ runner.temp }}"/${{ env.SNAP_NAME }}_*_amd64.snap .
        suites="${{ inputs.spread_suites }}"
        if [ -z "$suites" ]; then
            echo "Using default spread suite"
            spread google:
        else
            spread $suites
        fi
    - name: Discard spread workers
      shell: bash
      if: always()
      run: |
        shopt -s nullglob
        for r in .spread-reuse.*.yaml; do
            spread -discard -reuse-pid="$(printf "$r\n" | grep -o -E '[0-9]+')"
        done
